import { Product, Order } from "./types";
import { getProductImage } from "./get-product-image";

// Supplement product categories and names
const productNames = {
  protein: [
    "Whey Protein Isolate - Vanilla",
    "Whey Protein Concentrate - Chocolate",
    "Plant-Based Protein - Vanilla",
    "Casein Protein - Cookies & Cream",
    "Egg White Protein - Unflavored",
  ],
  vitamins: [
    "Vitamin D3 + K2 Complex",
    "Multivitamin for Men",
    "Multivitamin for Women",
    "Vitamin B12 Complex",
    "Omega-3 Fish Oil",
    "Vitamin C + Zinc",
  ],
  "pre-workout": [
    "Pre-Workout Energy - Caffeine Boost",
    "Pre-Workout Pump - Nitric Oxide",
    "Pre-Workout Endurance - Beta Alanine",
    "Pre-Workout Focus - No Caffeine",
  ],
  "post-workout": [
    "Post-Workout Recovery - BCAAs",
    "Post-Workout Glutamine",
    "Post-Workout Creatine Monohydrate",
  ],
  "weight-management": [
    "Fat Burner - Thermogenic",
    "Appetite Suppressant",
    "Metabolism Booster",
  ],
  "health-wellness": [
    "Probiotics - Digestive Health",
    "Magnesium Complex",
    "Collagen Peptides",
    "Turmeric Curcumin",
  ],
};

const descriptions = {
  protein: "High-quality protein powder to support muscle growth and recovery. Perfect for post-workout shakes or meal replacement.",
  vitamins: "Essential vitamins and minerals to support overall health and wellness. Formulated for optimal absorption.",
  "pre-workout": "Enhance your workout performance with this powerful pre-workout formula. Increases energy, focus, and endurance.",
  "post-workout": "Accelerate recovery and reduce muscle soreness with this post-workout supplement. Supports muscle repair and growth.",
  "weight-management": "Support your weight management goals with this scientifically-formulated supplement. Helps boost metabolism and control appetite.",
  "health-wellness": "Promote overall health and wellness with this premium supplement. Supports various aspects of your health journey.",
};


// Generate products with Unsplash image URLs
export const products: Product[] = [
  // Protein products
  {
    id: "prod-1",
    name: productNames.protein[0],
    description: descriptions.protein,
    price: 49.99,
    category: "protein",
    bestseller: true,
    image: getProductImage("protein", 0),
  },
  {
    id: "prod-2",
    name: productNames.protein[1],
    description: descriptions.protein,
    price: 44.99,
    category: "protein",
    bestseller: true,
    image: getProductImage("protein", 1),
  },
  {
    id: "prod-3",
    name: productNames.protein[2],
    description: descriptions.protein,
    price: 54.99,
    category: "protein",
    bestseller: false,
    image: getProductImage("protein", 2),
  },
  {
    id: "prod-4",
    name: productNames.protein[3],
    description: descriptions.protein,
    price: 52.99,
    category: "protein",
    bestseller: true,
    image: getProductImage("protein", 1),
  },
  {
    id: "prod-5",
    name: productNames.protein[4],
    description: descriptions.protein,
    price: 47.99,
    category: "protein",
    bestseller: false,
    image: getProductImage("protein", 0),
  },
  // Vitamin products
  {
    id: "prod-6",
    name: productNames.vitamins[0],
    description: descriptions.vitamins,
    price: 24.99,
    category: "vitamins",
    bestseller: true,
    image: getProductImage("vitamins", 0),
  },
  {
    id: "prod-7",
    name: productNames.vitamins[1],
    description: descriptions.vitamins,
    price: 29.99,
    category: "vitamins",
    bestseller: true,
    image: getProductImage("vitamins", 1),
  },
  {
    id: "prod-8",
    name: productNames.vitamins[2],
    description: descriptions.vitamins,
    price: 29.99,
    category: "vitamins",
    bestseller: false,
    image: getProductImage("vitamins", 0),
  },
  {
    id: "prod-9",
    name: productNames.vitamins[3],
    description: descriptions.vitamins,
    price: 19.99,
    category: "vitamins",
    bestseller: false,
    image: getProductImage("vitamins", 1),
  },
  {
    id: "prod-10",
    name: productNames.vitamins[4],
    description: descriptions.vitamins,
    price: 34.99,
    category: "vitamins",
    bestseller: true,
    image: getProductImage("vitamins", 0),
  },
  {
    id: "prod-11",
    name: productNames.vitamins[5],
    description: descriptions.vitamins,
    price: 22.99,
    category: "vitamins",
    bestseller: false,
    image: getProductImage("vitamins", 1),
  },
  // Pre-workout products
  {
    id: "prod-12",
    name: productNames["pre-workout"][0],
    description: descriptions["pre-workout"],
    price: 39.99,
    category: "pre-workout",
    bestseller: true,
    image: getProductImage("pre-workout", 0),
  },
  {
    id: "prod-13",
    name: productNames["pre-workout"][1],
    description: descriptions["pre-workout"],
    price: 42.99,
    category: "pre-workout",
    bestseller: false,
    image: getProductImage("pre-workout", 1),
  },
  {
    id: "prod-14",
    name: productNames["pre-workout"][2],
    description: descriptions["pre-workout"],
    price: 37.99,
    category: "pre-workout",
    bestseller: false,
    image: getProductImage("pre-workout", 2),
  },
  {
    id: "prod-15",
    name: productNames["pre-workout"][3],
    description: descriptions["pre-workout"],
    price: 39.99,
    category: "pre-workout",
    bestseller: false,
    image: getProductImage("pre-workout", 3),
  },
  // Post-workout products
  {
    id: "prod-16",
    name: productNames["post-workout"][0],
    description: descriptions["post-workout"],
    price: 32.99,
    category: "post-workout",
    bestseller: true,
    image: getProductImage("post-workout", 0),
  },
  {
    id: "prod-17",
    name: productNames["post-workout"][1],
    description: descriptions["post-workout"],
    price: 27.99,
    category: "post-workout",
    bestseller: false,
    image: getProductImage("post-workout", 1),
  },
  {
    id: "prod-18",
    name: productNames["post-workout"][2],
    description: descriptions["post-workout"],
    price: 24.99,
    category: "post-workout",
    bestseller: false,
    image: getProductImage("post-workout", 2),
  },
  // Weight management products
  {
    id: "prod-19",
    name: productNames["weight-management"][0],
    description: descriptions["weight-management"],
    price: 44.99,
    category: "weight-management",
    bestseller: false,
    image: getProductImage("weight-management", 0),
  },
  {
    id: "prod-20",
    name: productNames["weight-management"][1],
    description: descriptions["weight-management"],
    price: 39.99,
    category: "weight-management",
    bestseller: false,
    image: getProductImage("weight-management", 1),
  },
  {
    id: "prod-21",
    name: productNames["weight-management"][2],
    description: descriptions["weight-management"],
    price: 36.99,
    category: "weight-management",
    bestseller: false,
    image: getProductImage("weight-management", 2),
  },
  // Health & wellness products
  {
    id: "prod-22",
    name: productNames["health-wellness"][0],
    description: descriptions["health-wellness"],
    price: 29.99,
    category: "health-wellness",
    bestseller: true,
    image: getProductImage("health-wellness", 0),
  },
  {
    id: "prod-23",
    name: productNames["health-wellness"][1],
    description: descriptions["health-wellness"],
    price: 26.99,
    category: "health-wellness",
    bestseller: false,
    image: getProductImage("health-wellness", 1),
  },
  {
    id: "prod-24",
    name: productNames["health-wellness"][2],
    description: descriptions["health-wellness"],
    price: 49.99,
    category: "health-wellness",
    bestseller: false,
    image: getProductImage("health-wellness", 2),
  },
  {
    id: "prod-25",
    name: productNames["health-wellness"][3],
    description: descriptions["health-wellness"],
    price: 31.99,
    category: "health-wellness",
    bestseller: false,
    image: getProductImage("health-wellness", 3),
  },
];

// Generate sample orders
const getRandomDate = (daysAgo: number) => {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString();
};

const sampleCustomers = [
  { name: "John Smith", email: "john.smith@email.com", phone: "(555) 123-4567", address: "123 Main St", city: "New York", state: "NY", zipCode: "10001" },
  { name: "Sarah Johnson", email: "sarah.j@email.com", phone: "(555) 234-5678", address: "456 Oak Ave", city: "Los Angeles", state: "CA", zipCode: "90001" },
  { name: "Michael Brown", email: "m.brown@email.com", phone: "(555) 345-6789", address: "789 Pine Rd", city: "Chicago", state: "IL", zipCode: "60601" },
  { name: "Emily Davis", email: "emily.davis@email.com", phone: "(555) 456-7890", address: "321 Elm St", city: "Houston", state: "TX", zipCode: "77001" },
  { name: "David Wilson", email: "david.w@email.com", phone: "(555) 567-8901", address: "654 Maple Dr", city: "Phoenix", state: "AZ", zipCode: "85001" },
  { name: "Jessica Martinez", email: "j.martinez@email.com", phone: "(555) 678-9012", address: "987 Cedar Ln", city: "Philadelphia", state: "PA", zipCode: "19101" },
  { name: "Robert Taylor", email: "r.taylor@email.com", phone: "(555) 789-0123", address: "147 Birch Way", city: "San Antonio", state: "TX", zipCode: "78201" },
  { name: "Amanda Anderson", email: "amanda.a@email.com", phone: "(555) 890-1234", address: "258 Spruce Ct", city: "San Diego", state: "CA", zipCode: "92101" },
];

const statuses: Order["status"][] = ["pending", "processing", "shipped", "delivered", "cancelled"];

export const initialOrders: Order[] = [
  {
    id: "ORD-001",
    customerName: sampleCustomers[0].name,
    email: sampleCustomers[0].email,
    phone: sampleCustomers[0].phone,
    address: sampleCustomers[0].address,
    city: sampleCustomers[0].city,
    state: sampleCustomers[0].state,
    zipCode: sampleCustomers[0].zipCode,
    products: [
      { product: products[0], quantity: 2 },
      { product: products[5], quantity: 1 },
    ],
    status: "delivered",
    date: getRandomDate(15),
    total: 124.97,
  },
  {
    id: "ORD-002",
    customerName: sampleCustomers[1].name,
    email: sampleCustomers[1].email,
    phone: sampleCustomers[1].phone,
    address: sampleCustomers[1].address,
    city: sampleCustomers[1].city,
    state: sampleCustomers[1].state,
    zipCode: sampleCustomers[1].zipCode,
    products: [
      { product: products[1], quantity: 1 },
      { product: products[11], quantity: 1 },
    ],
    status: "shipped",
    date: getRandomDate(8),
    total: 87.98,
  },
  {
    id: "ORD-003",
    customerName: sampleCustomers[2].name,
    email: sampleCustomers[2].email,
    phone: sampleCustomers[2].phone,
    address: sampleCustomers[2].address,
    city: sampleCustomers[2].city,
    state: sampleCustomers[2].state,
    zipCode: sampleCustomers[2].zipCode,
    products: [{ product: products[2], quantity: 1 }],
    status: "processing",
    date: getRandomDate(5),
    total: 54.99,
  },
  {
    id: "ORD-004",
    customerName: sampleCustomers[3].name,
    email: sampleCustomers[3].email,
    phone: sampleCustomers[3].phone,
    address: sampleCustomers[3].address,
    city: sampleCustomers[3].city,
    state: sampleCustomers[3].state,
    zipCode: sampleCustomers[3].zipCode,
    products: [
      { product: products[6], quantity: 2 },
      { product: products[9], quantity: 1 },
    ],
    status: "pending",
    date: getRandomDate(2),
    total: 94.97,
  },
  {
    id: "ORD-005",
    customerName: sampleCustomers[4].name,
    email: sampleCustomers[4].email,
    phone: sampleCustomers[4].phone,
    address: sampleCustomers[4].address,
    city: sampleCustomers[4].city,
    state: sampleCustomers[4].state,
    zipCode: sampleCustomers[4].zipCode,
    products: [
      { product: products[3], quantity: 1 },
      { product: products[15], quantity: 1 },
      { product: products[21], quantity: 1 },
    ],
    status: "delivered",
    date: getRandomDate(20),
    total: 128.97,
  },
  {
    id: "ORD-006",
    customerName: sampleCustomers[5].name,
    email: sampleCustomers[5].email,
    phone: sampleCustomers[5].phone,
    address: sampleCustomers[5].address,
    city: sampleCustomers[5].city,
    state: sampleCustomers[5].state,
    zipCode: sampleCustomers[5].zipCode,
    products: [{ product: products[7], quantity: 1 }],
    status: "cancelled",
    date: getRandomDate(10),
    total: 29.99,
  },
  {
    id: "ORD-007",
    customerName: sampleCustomers[6].name,
    email: sampleCustomers[6].email,
    phone: sampleCustomers[6].phone,
    address: sampleCustomers[6].address,
    city: sampleCustomers[6].city,
    state: sampleCustomers[6].state,
    zipCode: sampleCustomers[6].zipCode,
    products: [
      { product: products[4], quantity: 1 },
      { product: products[8], quantity: 2 },
    ],
    status: "shipped",
    date: getRandomDate(6),
    total: 97.97,
  },
  {
    id: "ORD-008",
    customerName: sampleCustomers[7].name,
    email: sampleCustomers[7].email,
    phone: sampleCustomers[7].phone,
    address: sampleCustomers[7].address,
    city: sampleCustomers[7].city,
    state: sampleCustomers[7].state,
    zipCode: sampleCustomers[7].zipCode,
    products: [
      { product: products[10], quantity: 1 },
      { product: products[12], quantity: 1 },
    ],
    status: "processing",
    date: getRandomDate(3),
    total: 79.98,
  },
  {
    id: "ORD-009",
    customerName: sampleCustomers[0].name,
    email: sampleCustomers[0].email,
    phone: sampleCustomers[0].phone,
    address: sampleCustomers[0].address,
    city: sampleCustomers[0].city,
    state: sampleCustomers[0].state,
    zipCode: sampleCustomers[0].zipCode,
    products: [{ product: products[13], quantity: 1 }],
    status: "pending",
    date: getRandomDate(1),
    total: 39.99,
  },
  {
    id: "ORD-010",
    customerName: sampleCustomers[2].name,
    email: sampleCustomers[2].email,
    phone: sampleCustomers[2].phone,
    address: sampleCustomers[2].address,
    city: sampleCustomers[2].city,
    state: sampleCustomers[2].state,
    zipCode: sampleCustomers[2].zipCode,
    products: [
      { product: products[14], quantity: 1 },
      { product: products[16], quantity: 1 },
    ],
    status: "delivered",
    date: getRandomDate(12),
    total: 60.98,
  },
];

